In [11]:
import pandas as pd

from sklearn.datasets import load_iris

iris = load_iris()

print(f'iris.data : {iris.data}')
print(f'iris.feature : {iris.feature_names}')
print('--')
print(f'iris.target : {iris.target}')
print(f'iris.target_names : {iris.target_names}')


iris.data : [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]


In [10]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [12]:
type(iris.data)

numpy.ndarray

In [13]:
df = pd.DataFrame(iris.data, columns=iris.feature_names,)

df['species'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

# 열 이름 변경하기

- df.columns에 모두 입력
- df.rename(columns=dict())로 지정한 컬럼만 변경

In [14]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'species'],
      dtype='object')

In [15]:
df.columns = ['sl', 'sw', 'pl', 'pw', 'sp']
df.head()

sl   sw   pl   pw  sp
0  5.1  3.5  1.4  0.2   0
1  4.9  3.0  1.4  0.2   0
2  4.7  3.2  1.3  0.2   0
3  4.6  3.1  1.5  0.2   0
4  5.0  3.6  1.4  0.2   0

In [16]:
df.rename(columns={'sp' : 's'}, inplace=True)
df.head()

sl   sw   pl   pw  s
0  5.1  3.5  1.4  0.2  0
1  4.9  3.0  1.4  0.2  0
2  4.7  3.2  1.3  0.2  0
3  4.6  3.1  1.5  0.2  0
4  5.0  3.6  1.4  0.2  0

# 특정 데이터만 추출하기

In [18]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [19]:
df[0:4]

sl   sw   pl   pw  s
0  5.1  3.5  1.4  0.2  0
1  4.9  3.0  1.4  0.2  0
2  4.7  3.2  1.3  0.2  0
3  4.6  3.1  1.5  0.2  0

In [23]:
df[['sl', 'pl', 's']]

sl   pl  s
0    5.1  1.4  0
1    4.9  1.4  0
2    4.7  1.3  0
3    4.6  1.5  0
4    5.0  1.4  0
..   ...  ... ..
145  6.7  5.2  2
146  6.3  5.0  2
147  6.5  5.2  2
148  6.2  5.4  2
149  5.9  5.1  2

[150 rows x 3 columns]

In [26]:
df[0:4][['sl', 's']]

sl  s
0  5.1  0
1  4.9  0
2  4.7  0
3  4.6  0

## 데이터셋 분리 해보기

In [29]:
df_1 = df[df.s == 1]
df_1.info()
display(df_1.tail())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 50 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   sl      50 non-null     float64
 1   sw      50 non-null     float64
 2   pl      50 non-null     float64
 3   pw      50 non-null     float64
 4   s       50 non-null     int64  
dtypes: float64(4), int64(1)
memory usage: 2.3 KB


sl   sw   pl   pw  s
95  5.7  3.0  4.2  1.2  1
96  5.7  2.9  4.2  1.3  1
97  6.2  2.9  4.3  1.3  1
98  5.1  2.5  3.0  1.1  1
99  5.7  2.8  4.1  1.3  1

In [33]:
df_2 = df.loc[(df.sl > 6) & (df.s == 1), :]
df_2.head()

sl   sw   pl   pw  s
50  7.0  3.2  4.7  1.4  1
51  6.4  3.2  4.5  1.5  1
52  6.9  3.1  4.9  1.5  1
54  6.5  2.8  4.6  1.5  1
56  6.3  3.3  4.7  1.6  1

In [34]:
df_3 = df.loc[df.s == 0, ['sl', 'sw', 's']]
df_3.head()

sl   sw  s
0  5.1  3.5  0
1  4.9  3.0  0
2  4.7  3.2  0
3  4.6  3.1  0
4  5.0  3.6  0

# numpy

In [45]:
import numpy as np

# scalar
a0 = np.array(1)
print(f'a0 = {a0}')

# vector
a1 = np.array([1, 2])
print(f'a1 = {a1}')

# array
a2 = np.array(([1, 2] , [3, 4]))
print(f'a2 = {a2}')

# tensor
a3 = np.array(([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print(f'a3 = {a3}')

a0 = 1
a1 = [1 2]
a2 = [[1 2]
 [3 4]]
a3 = [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
a3.shape

(2, 2, 2)

# 데이터 정제


## 에어코리아 종로 측정소 데이터 활용 - 결측치 확인

In [48]:
import pandas as pd

air = pd.read_csv('./dataset/ch3-1.csv')
air

MMDDHH  PM10  PM25     O3    NO2   CO    SO2
0   06-01-01  28.0  18.0  0.039  0.009  0.3  0.002
1   06-01-02  19.0  14.0  0.041  0.007  0.3  0.002
2   06-01-03  15.0  13.0  0.043  0.006  0.3  0.002
3   06-01-04  16.0  13.0  0.042  0.006  0.3  0.002
4   06-01-05  14.0  11.0  0.041  0.008  0.3  0.003
5   06-01-06  14.0  10.0  0.040  0.009  0.3  0.003
6   06-01-07  15.0  10.0  0.038  0.014  0.3  0.002
7   06-01-08  20.0  10.0  0.034  0.019  0.3  0.002
8   06-01-09  28.0  15.0  0.032  0.022  0.4  0.003
9   06-01-10  28.0  12.0  0.035  0.017  0.4  0.003
10  06-01-11  29.0   9.0  0.038  0.015  0.4  0.003
11  06-01-12  32.0  11.0  0.039  0.012  0.3  0.003
12  06-01-13  32.0  11.0  0.038  0.015  0.3  0.003
13  06-01-14   NaN   NaN    NaN    NaN  NaN    NaN
14  06-01-15   NaN   NaN    NaN    NaN  NaN    NaN
15  06-01-16   NaN   NaN  0.038  0.020  0.4  0.003
16  06-01-17  27.0  12.0  0.041  0.022  0.4  0.003
17  06-01-18  24.0  14.0  0.048  0.016  0.4  0.003
18  06-01-19  25.0  12.0  0.048  0.014  0.3  0.003
19  06-01-20  26.0  14.0  0.043  0.020  0.4  0.003
20  06-01-21  28.0  15.0  0.049  0.017  0.4  0.003
21  06-01-22  25.0  13.0  0.045  0.020  0.4  0.003
22  06-01-23  29.0  14.0  0.035  0.023  0.4  0.003
23  06-01-24  25.0  15.0  0.028  0.027  0.4  0.003

In [80]:
air.loc[air.isnull().sum(axis=1) > 0, :]

MMDDHH  PM10  PM25     O3   NO2   CO    SO2
13  06-01-14   NaN   NaN    NaN   NaN  NaN    NaN
14  06-01-15   NaN   NaN    NaN   NaN  NaN    NaN
15  06-01-16   NaN   NaN  0.038  0.02  0.4  0.003

## 결측치 제거하기

In [81]:
air_d = air.dropna(axis = 0) # 0 : 행제거 / 1 : 열제거
air_d

MMDDHH  PM10  PM25     O3    NO2   CO    SO2
0   06-01-01  28.0  18.0  0.039  0.009  0.3  0.002
1   06-01-02  19.0  14.0  0.041  0.007  0.3  0.002
2   06-01-03  15.0  13.0  0.043  0.006  0.3  0.002
3   06-01-04  16.0  13.0  0.042  0.006  0.3  0.002
4   06-01-05  14.0  11.0  0.041  0.008  0.3  0.003
5   06-01-06  14.0  10.0  0.040  0.009  0.3  0.003
6   06-01-07  15.0  10.0  0.038  0.014  0.3  0.002
7   06-01-08  20.0  10.0  0.034  0.019  0.3  0.002
8   06-01-09  28.0  15.0  0.032  0.022  0.4  0.003
9   06-01-10  28.0  12.0  0.035  0.017  0.4  0.003
10  06-01-11  29.0   9.0  0.038  0.015  0.4  0.003
11  06-01-12  32.0  11.0  0.039  0.012  0.3  0.003
12  06-01-13  32.0  11.0  0.038  0.015  0.3  0.003
16  06-01-17  27.0  12.0  0.041  0.022  0.4  0.003
17  06-01-18  24.0  14.0  0.048  0.016  0.4  0.003
18  06-01-19  25.0  12.0  0.048  0.014  0.3  0.003
19  06-01-20  26.0  14.0  0.043  0.020  0.4  0.003
20  06-01-21  28.0  15.0  0.049  0.017  0.4  0.003
21  06-01-22  25.0  13.0  0.045  0.020  0.4  0.003
22  06-01-23  29.0  14.0  0.035  0.023  0.4  0.003
23  06-01-24  25.0  15.0  0.028  0.027  0.4  0.003

## 결측치 - 평균으로 대체

In [82]:
air.mean()

<ipython-input-82-b23cf9cb2327>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  air.mean()


PM10    23.761905
PM25    12.666667
O3       0.039773
NO2      0.015364
CO       0.350000
SO2      0.002727
dtype: float64

In [86]:
air_m = air.fillna(air.mean())
display(air_m)

air_d = air.fillna(air.median())
display(air_d)

<ipython-input-86-b6a5f7e6d6f7>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  air_m = air.fillna(air.mean())


MMDDHH       PM10       PM25        O3       NO2    CO       SO2
0   06-01-01  28.000000  18.000000  0.039000  0.009000  0.30  0.002000
1   06-01-02  19.000000  14.000000  0.041000  0.007000  0.30  0.002000
2   06-01-03  15.000000  13.000000  0.043000  0.006000  0.30  0.002000
3   06-01-04  16.000000  13.000000  0.042000  0.006000  0.30  0.002000
4   06-01-05  14.000000  11.000000  0.041000  0.008000  0.30  0.003000
5   06-01-06  14.000000  10.000000  0.040000  0.009000  0.30  0.003000
6   06-01-07  15.000000  10.000000  0.038000  0.014000  0.30  0.002000
7   06-01-08  20.000000  10.000000  0.034000  0.019000  0.30  0.002000
8   06-01-09  28.000000  15.000000  0.032000  0.022000  0.40  0.003000
9   06-01-10  28.000000  12.000000  0.035000  0.017000  0.40  0.003000
10  06-01-11  29.000000   9.000000  0.038000  0.015000  0.40  0.003000
11  06-01-12  32.000000  11.000000  0.039000  0.012000  0.30  0.003000
12  06-01-13  32.000000  11.000000  0.038000  0.015000  0.30  0.003000
13  06-01-14  23.761905  12.666667  0.039773  0.015364  0.35  0.002727
14  06-01-15  23.761905  12.666667  0.039773  0.015364  0.35  0.002727
15  06-01-16  23.761905  12.666667  0.038000  0.020000  0.40  0.003000
16  06-01-17  27.000000  12.000000  0.041000  0.022000  0.40  0.003000
17  06-01-18  24.000000  14.000000  0.048000  0.016000  0.40  0.003000
18  06-01-19  25.000000  12.000000  0.048000  0.014000  0.30  0.003000
19  06-01-20  26.000000  14.000000  0.043000  0.020000  0.40  0.003000
20  06-01-21  28.000000  15.000000  0.049000  0.017000  0.40  0.003000
21  06-01-22  25.000000  13.000000  0.045000  0.020000  0.40  0.003000
22  06-01-23  29.000000  14.000000  0.035000  0.023000  0.40  0.003000
23  06-01-24  25.000000  15.000000  0.028000  0.027000  0.40  0.003000

<ipython-input-86-b6a5f7e6d6f7>:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  air_d = air.fillna(air.median())


MMDDHH  PM10  PM25      O3     NO2    CO    SO2
0   06-01-01  28.0  18.0  0.0390  0.0090  0.30  0.002
1   06-01-02  19.0  14.0  0.0410  0.0070  0.30  0.002
2   06-01-03  15.0  13.0  0.0430  0.0060  0.30  0.002
3   06-01-04  16.0  13.0  0.0420  0.0060  0.30  0.002
4   06-01-05  14.0  11.0  0.0410  0.0080  0.30  0.003
5   06-01-06  14.0  10.0  0.0400  0.0090  0.30  0.003
6   06-01-07  15.0  10.0  0.0380  0.0140  0.30  0.002
7   06-01-08  20.0  10.0  0.0340  0.0190  0.30  0.002
8   06-01-09  28.0  15.0  0.0320  0.0220  0.40  0.003
9   06-01-10  28.0  12.0  0.0350  0.0170  0.40  0.003
10  06-01-11  29.0   9.0  0.0380  0.0150  0.40  0.003
11  06-01-12  32.0  11.0  0.0390  0.0120  0.30  0.003
12  06-01-13  32.0  11.0  0.0380  0.0150  0.30  0.003
13  06-01-14  25.0  13.0  0.0395  0.0155  0.35  0.003
14  06-01-15  25.0  13.0  0.0395  0.0155  0.35  0.003
15  06-01-16  25.0  13.0  0.0380  0.0200  0.40  0.003
16  06-01-17  27.0  12.0  0.0410  0.0220  0.40  0.003
17  06-01-18  24.0  14.0  0.0480  0.0160  0.40  0.003
18  06-01-19  25.0  12.0  0.0480  0.0140  0.30  0.003
19  06-01-20  26.0  14.0  0.0430  0.0200  0.40  0.003
20  06-01-21  28.0  15.0  0.0490  0.0170  0.40  0.003
21  06-01-22  25.0  13.0  0.0450  0.0200  0.40  0.003
22  06-01-23  29.0  14.0  0.0350  0.0230  0.40  0.003
23  06-01-24  25.0  15.0  0.0280  0.0270  0.40  0.003

## 이상치(Outlier)

- 정규분포 2표준편차 이상/이하
- IQR
- boxplot

## 스케일링

- Min-Max
- Standard
- robust